// <auto-generated />
using System;
using ETL.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ETL.Migrations
{
    [DbContext(typeof(ApplicationDbContext.ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ETL.Entity.AnbarResidHavaleDetailModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Anbar")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("DetailedType")
                        .HasColumnType("text");

                    b.Property<string>("FactorNum")
                        .HasColumnType("text");

                    b.Property<string>("Fee")
                        .HasColumnType("text");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("KDesc")
                        .HasColumnType("text");

                    b.Property<string>("KalaCode")
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<string>("RHActionDesc")
                        .HasColumnType("text");

                    b.Property<string>("RHDesc")
                        .HasColumnType("text");

                    b.Property<string>("RowIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue1")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue2")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue3")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("ProductRecords");
                });

            modelBuilder.Entity("ETL.Entity.CounterPartyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Active")
                        .HasColumnType("text");

                    b.Property<string>("CounterPartyCode")
                        .HasColumnType("text");

                    b.Property<string>("CusotmerFamily")
                        .HasColumnType("text");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("text");

                    b.Property<string>("CustomerBirthDay")
                        .HasColumnType("text");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("text");

                    b.Property<string>("CustomerIdentiifre")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPelak")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("CustomerTel")
                        .HasColumnType("text");

                    b.Property<string>("CustomerType")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("HesabAnbar")
                        .HasColumnType("text");

                    b.Property<string>("HesabID")
                        .HasColumnType("text");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("RowIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CounterParties");
                });

            modelBuilder.Entity("ETL.Entity.HesabSummaryModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Bedehkar")
                        .HasColumnType("text");

                    b.Property<string>("Bestankar")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RowIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HesabRecords");
                });

            modelBuilder.Entity("ETL.Entity.SaleRecordModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .HasColumnType("text");

                    b.Property<string>("Active")
                        .HasColumnType("text");

                    b.Property<string>("Article")
                        .HasColumnType("text");

                    b.Property<string>("CusotmerFamily")
                        .HasColumnType("text");

                    b.Property<string>("CustomerAccount")
                        .HasColumnType("text");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("text");

                    b.Property<string>("CustomerBirthDay")
                        .HasColumnType("text");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("text");

                    b.Property<string>("CustomerIdentiifre")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPelak")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("CustomerTel")
                        .HasColumnType("text");

                    b.Property<string>("CustomerType")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("DetailedType")
                        .HasColumnType("text");

                    b.Property<string>("DocNum")
                        .HasColumnType("text");

                    b.Property<string>("HavaleCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("KDesc")
                        .HasColumnType("text");

                    b.Property<string>("KalDelimiter")
                        .HasColumnType("text");

                    b.Property<string>("KalaCode")
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<string>("RowIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SandID")
                        .HasColumnType("text");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TarafHesab")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UnitCode1")
                        .HasColumnType("text");

                    b.Property<string>("UnitCode2")
                        .HasColumnType("text");

                    b.Property<string>("UnitCode3")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue1")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue2")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue3")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaleRecords");
                });

            modelBuilder.Entity("ETL.Entity.SaleReturnRecordModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .HasColumnType("text");

                    b.Property<string>("Active")
                        .HasColumnType("text");

                    b.Property<string>("Article")
                        .HasColumnType("text");

                    b.Property<string>("CusotmerFamily")
                        .HasColumnType("text");

                    b.Property<string>("CustomerAccount")
                        .HasColumnType("text");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("text");

                    b.Property<string>("CustomerBirthDay")
                        .HasColumnType("text");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("text");

                    b.Property<string>("CustomerIdentiifre")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPelak")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("CustomerTel")
                        .HasColumnType("text");

                    b.Property<string>("CustomerType")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("DetailedType")
                        .HasColumnType("text");

                    b.Property<string>("DocNum")
                        .HasColumnType("text");

                    b.Property<string>("HavaleCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("KDesc")
                        .HasColumnType("text");

                    b.Property<string>("KalDelimiter")
                        .HasColumnType("text");

                    b.Property<string>("KalaCode")
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<string>("RowIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SandID")
                        .HasColumnType("text");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TarafHesab")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UnitCode1")
                        .HasColumnType("text");

                    b.Property<string>("UnitCode2")
                        .HasColumnType("text");

                    b.Property<string>("UnitCode3")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue1")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue2")
                        .HasColumnType("text");

                    b.Property<string>("UnitValue3")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaleReturnRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
